#############################################################################
# Generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#  May 08, 2022 11:28:45 PM +07  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #e4e4e4 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 520x437+851+225
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Search Flight"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Search_page" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    button $top.but46 \
        -activebackground #80ff00 -activeforeground #000000 \
        -background #b3ff66 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Search 
    vTcl:DefineAlias "$top.but46" "Button_search" vTcl:WidgetProc "Search_page" 1
    label $top.lab47 \
        -activebackground #e4e4e4 -activeforeground black -background #e4e4e4 \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Search Flight} 
    vTcl:DefineAlias "$top.lab47" "Label_search" vTcl:WidgetProc "Search_page" 1
    label $top.lab48 \
        -activebackground #e4e4e4 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Depart from} 
    vTcl:DefineAlias "$top.lab48" "Label_depart" vTcl:WidgetProc "Search_page" 1
    label $top.lab49 \
        -activebackground #e4e4e4 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Fly to} 
    vTcl:DefineAlias "$top.lab49" "Label_fly" vTcl:WidgetProc "Search_page" 1
    label $top.lab50 \
        -activebackground #e4e4e4 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Date 
    vTcl:DefineAlias "$top.lab50" "Label_date" vTcl:WidgetProc "Search_page" 1
    ttk::combobox $top.tCo51 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo51" "Combobox_depart" vTcl:WidgetProc "Search_page" 1
    ttk::combobox $top.tCo52 \
        -font TkTextFont -textvariable combobox -foreground {} -background {} \
        -takefocus {} 
    vTcl:DefineAlias "$top.tCo52" "Combobox_fly" vTcl:WidgetProc "Search_page" 1
    entry $top.ent53 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent53" "Entry_date" vTcl:WidgetProc "Search_page" 1
    button $top.but49 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text History 
    vTcl:DefineAlias "$top.but49" "Button_history" vTcl:WidgetProc "Search_page" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but46 \
        -in $top -x 0 -relx 0.385 -y 0 -rely 0.778 -width 137 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.269 -y 0 -rely 0.069 -width 0 -relwidth 0.508 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.183 -width 0 -relwidth 0.546 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.389 -width 0 -relwidth 0.546 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.595 -width 0 -relwidth 0.546 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tCo51 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.252 -width 0 -relwidth 0.544 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.tCo52 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.458 -width 0 -relwidth 0.544 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.ent53 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.664 -width 283 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but49 \
        -in $top -x 0 -relx 0.846 -y 0 -rely 0.046 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top2 {base} {
    global vTcl
    if {$base == ""} {
        set base .top2
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #e4e4e4 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 520x437+408+108
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Flights"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Flight_page" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    button $top.but54 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text BACK 
    vTcl:DefineAlias "$top.but54" "Button_back" vTcl:WidgetProc "Flight_page" 1
    label $top.lab55 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Depart from} 
    vTcl:DefineAlias "$top.lab55" "Label_depart" vTcl:WidgetProc "Flight_page" 1
    label $top.lab56 \
        -activebackground #e4e4e4 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text XXX 
    vTcl:DefineAlias "$top.lab56" "Label_origin" vTcl:WidgetProc "Flight_page" 1
    label $top.lab57 \
        -activebackground #e4e4e4 -activeforeground black -background #e4e4e4 \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Arrive at} 
    vTcl:DefineAlias "$top.lab57" "Label_to" vTcl:WidgetProc "Flight_page" 1
    label $top.lab58 \
        -activebackground #e4e4e4 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text XXX 
    vTcl:DefineAlias "$top.lab58" "Label_destination" vTcl:WidgetProc "Flight_page" 1
    frame $top.fra59 \
        -borderwidth 2 -relief groove -background #ffffff -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 435 
    vTcl:DefineAlias "$top.fra59" "Frame1" vTcl:WidgetProc "Flight_page" 1
    set site_3_0 $top.fra59
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 00:00 
    vTcl:DefineAlias "$site_3_0.lab60" "Label_timestart1" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text XXX 
    vTcl:DefineAlias "$site_3_0.lab61" "Label_origin1" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text > 
    vTcl:DefineAlias "$site_3_0.lab62" "Label1" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 00:00 
    vTcl:DefineAlias "$site_3_0.lab63" "Label_timearrival1" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab64 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text XXX 
    vTcl:DefineAlias "$site_3_0.lab64" "Label_destination1" vTcl:WidgetProc "Flight_page" 1
    button $site_3_0.but65 \
        -activebackground #80ff00 -activeforeground #000000 \
        -background #b3ff66 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text CHOOSE 
    vTcl:DefineAlias "$site_3_0.but65" "Button_choose1" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab66 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 0000 
    vTcl:DefineAlias "$site_3_0.lab66" "Label_price1" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Baht 
    vTcl:DefineAlias "$site_3_0.lab68" "Label_baht1" vTcl:WidgetProc "Flight_page" 1
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.092 -y 0 -rely 0.267 -width 0 \
        -relwidth 0.08 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.046 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.172 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 0 -relx 0.23 -y 0 -rely 0.267 -width 0 \
        -relwidth 0.08 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx 0.368 -y 0 -rely 0.267 -width 0 \
        -relwidth 0.08 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 0 -relx 0.322 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.172 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but65 \
        -in $site_3_0 -x 0 -relx 0.759 -y 0 -rely 0.267 -width 77 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 0 -relx 0.575 -y 0 -rely 0.267 -width 0 \
        -relwidth 0.172 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.621 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.08 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    frame $top.fra69 \
        -borderwidth 2 -relief groove -background #ffffff -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 435 
    vTcl:DefineAlias "$top.fra69" "Frame2" vTcl:WidgetProc "Flight_page" 1
    set site_3_0 $top.fra69
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 00:00 
    vTcl:DefineAlias "$site_3_0.lab60" "Label_timestart2" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text XXX 
    vTcl:DefineAlias "$site_3_0.lab61" "Label_origin2" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text > 
    vTcl:DefineAlias "$site_3_0.lab62" "Label1" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 00:00 
    vTcl:DefineAlias "$site_3_0.lab63" "Label_timearrival2" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab64 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text XXX 
    vTcl:DefineAlias "$site_3_0.lab64" "Label_destination2" vTcl:WidgetProc "Flight_page" 1
    button $site_3_0.but65 \
        -activebackground #80ff00 -activeforeground #000000 \
        -background #b3ff66 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text CHOOSE 
    vTcl:DefineAlias "$site_3_0.but65" "Button_choose2" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab66 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 0000 
    vTcl:DefineAlias "$site_3_0.lab66" "Label_price2" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Baht 
    vTcl:DefineAlias "$site_3_0.lab68" "Label_baht2" vTcl:WidgetProc "Flight_page" 1
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.092 -y 0 -rely 0.267 -width 0 \
        -relwidth 0.08 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.046 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.172 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 0 -relx 0.23 -y 0 -rely 0.267 -width 0 \
        -relwidth 0.08 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx 0.368 -y 0 -rely 0.267 -width 0 \
        -relwidth 0.08 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 0 -relx 0.322 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.172 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but65 \
        -in $site_3_0 -x 0 -relx 0.759 -y 0 -rely 0.267 -width 77 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 0 -relx 0.575 -y 0 -rely 0.267 -width 0 \
        -relwidth 0.172 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.621 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.08 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    frame $top.fra70 \
        -borderwidth 2 -relief groove -background #ffffff -height 75 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -width 435 
    vTcl:DefineAlias "$top.fra70" "Frame3" vTcl:WidgetProc "Flight_page" 1
    set site_3_0 $top.fra70
    label $site_3_0.lab60 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 00:00 
    vTcl:DefineAlias "$site_3_0.lab60" "Label_timestart3" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab61 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text XXX 
    vTcl:DefineAlias "$site_3_0.lab61" "Label_origin3" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text > 
    vTcl:DefineAlias "$site_3_0.lab62" "Label1_1" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 00:00 
    vTcl:DefineAlias "$site_3_0.lab63" "Label_timearrival3" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab64 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text XXX 
    vTcl:DefineAlias "$site_3_0.lab64" "Label_destination3" vTcl:WidgetProc "Flight_page" 1
    button $site_3_0.but65 \
        -activebackground #80ff00 -activeforeground #000000 \
        -background #b3ff66 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text CHOOSE 
    vTcl:DefineAlias "$site_3_0.but65" "Button_choose3" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab66 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 0000 
    vTcl:DefineAlias "$site_3_0.lab66" "Label_price3" vTcl:WidgetProc "Flight_page" 1
    label $site_3_0.lab68 \
        -activebackground #f9f9f9 -activeforeground black -background #ffffff \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Baht 
    vTcl:DefineAlias "$site_3_0.lab68" "Label_baht3" vTcl:WidgetProc "Flight_page" 1
    place $site_3_0.lab60 \
        -in $site_3_0 -x 0 -relx 0.092 -y 0 -rely 0.267 -width 0 \
        -relwidth 0.08 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab61 \
        -in $site_3_0 -x 0 -relx 0.046 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.172 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 0 -relx 0.23 -y 0 -rely 0.267 -width 0 \
        -relwidth 0.08 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx 0.368 -y 0 -rely 0.267 -width 0 \
        -relwidth 0.08 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 0 -relx 0.322 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.172 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but65 \
        -in $site_3_0 -x 0 -relx 0.759 -y 0 -rely 0.267 -width 77 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 0 -relx 0.575 -y 0 -rely 0.267 -width 0 \
        -relwidth 0.172 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.621 -y 0 -rely 0.533 -width 0 \
        -relwidth 0.08 -height 0 -relheight 0.28 -anchor nw \
        -bordermode ignore 
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text History 
    vTcl:DefineAlias "$top.but46" "Button_history" vTcl:WidgetProc "Flight_page" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but54 \
        -in $top -x 0 -relx 0.038 -y 0 -rely 0.046 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 0 -relx 0.096 -y 0 -rely 0.137 -width 0 -relwidth 0.162 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.137 -width 0 -relwidth 0.065 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.327 -y 0 -rely 0.137 -width 0 -relwidth 0.123 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab58 \
        -in $top -x 0 -relx 0.462 -y 0 -rely 0.137 -width 0 -relwidth 0.065 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.fra59 \
        -in $top -x 0 -relx 0.077 -y 0 -rely 0.206 -width 0 -relwidth 0.837 \
        -height 0 -relheight 0.172 -anchor nw -bordermode ignore 
    place $top.fra69 \
        -in $top -x 0 -relx 0.077 -y 0 -rely 0.435 -width 0 -relwidth 0.837 \
        -height 0 -relheight 0.172 -anchor nw -bordermode ignore 
    place $top.fra70 \
        -in $top -x 0 -relx 0.077 -y 0 -rely 0.664 -width 0 -relwidth 0.837 \
        -height 0 -relheight 0.172 -anchor nw -bordermode ignore 
    place $top.but46 \
        -in $top -x 0 -relx 0.865 -y 0 -rely 0.046 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top3 {base} {
    global vTcl
    if {$base == ""} {
        set base .top3
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #e4e4e4 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 520x438+759+476
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Login"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Login_page" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab71 \
        -activebackground #e4e4e4 -activeforeground black -background #e4e4e4 \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text LOGIN 
    vTcl:DefineAlias "$top.lab71" "Label_login" vTcl:WidgetProc "Login_page" 1
    label $top.lab72 \
        -activebackground #e4e4e4 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {User Name} 
    vTcl:DefineAlias "$top.lab72" "Label_user" vTcl:WidgetProc "Login_page" 1
    label $top.lab73 \
        -activebackground #e4e4e4 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Password 
    vTcl:DefineAlias "$top.lab73" "Label_pass" vTcl:WidgetProc "Login_page" 1
    button $top.but74 \
        -activebackground #2c62b4 -activeforeground #ffffff \
        -background #0080ff -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground #ffffff -highlightbackground #0080ff \
        -highlightcolor #000000 -pady 0 -text LOGIN 
    vTcl:DefineAlias "$top.but74" "Button_login" vTcl:WidgetProc "Login_page" 1
    button $top.but75 \
        -activebackground #00ff40 -activeforeground #000000 \
        -background #b3ff66 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text REGISTER 
    vTcl:DefineAlias "$top.but75" "Button1" vTcl:WidgetProc "Login_page" 1
    label $top.lab77 \
        -activebackground #e4e4e4 -activeforeground black -background #e4e4e4 \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text -------------------------------------- 
    vTcl:DefineAlias "$top.lab77" "Label1" vTcl:WidgetProc "Login_page" 1
    entry $top.ent78 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 254 
    vTcl:DefineAlias "$top.ent78" "Entry_user" vTcl:WidgetProc "Login_page" 1
    entry $top.ent79 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent79" "Entry_pass" vTcl:WidgetProc "Login_page" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab71 \
        -in $top -x 0 -relx 0.192 -y 0 -rely 0.046 -width 0 -relwidth 0.604 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab72 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.114 -width 0 -relwidth 0.488 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab73 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.275 -width 0 -relwidth 0.488 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.but74 \
        -in $top -x 0 -relx 0.365 -y 0 -rely 0.435 -width 127 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but75 \
        -in $top -x 0 -relx 0.404 -y 0 -rely 0.618 -width 87 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab77 \
        -in $top -x 0 -relx 0.288 -y 0 -rely 0.549 -width 0 -relwidth 0.412 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.ent78 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.183 -width 254 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent79 \
        -in $top -x 0 -relx 0.25 -y 0 -rely 0.343 -width 254 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top4 {base} {
    global vTcl
    if {$base == ""} {
        set base .top4
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #e4e4e4 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 520x437+826+232
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Register"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Register_page" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab46 \
        -activebackground #e4e4e4 -activeforeground black -background #e4e4e4 \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Register 
    vTcl:DefineAlias "$top.lab46" "Label_register" vTcl:WidgetProc "Register_page" 1
    label $top.lab47 \
        -activebackground #e4e4e4 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {ID Card} 
    vTcl:DefineAlias "$top.lab47" "Label_ID" vTcl:WidgetProc "Register_page" 1
    label $top.lab48 \
        -activebackground #e4e4e4 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Phone Number} 
    vTcl:DefineAlias "$top.lab48" "Label_phone" vTcl:WidgetProc "Register_page" 1
    label $top.lab49 \
        -activebackground #e4e4e4 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {User Name} 
    vTcl:DefineAlias "$top.lab49" "Label_user" vTcl:WidgetProc "Register_page" 1
    label $top.lab50 \
        -activebackground #e4e4e4 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Password 
    vTcl:DefineAlias "$top.lab50" "Label_pass" vTcl:WidgetProc "Register_page" 1
    label $top.lab51 \
        -activebackground #e4e4e4 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Confirm Password} 
    vTcl:DefineAlias "$top.lab51" "Label_repass" vTcl:WidgetProc "Register_page" 1
    button $top.but52 \
        -activebackground #00ff40 -activeforeground #000000 \
        -background #b3ff66 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text REGISTER 
    vTcl:DefineAlias "$top.but52" "Button_register" vTcl:WidgetProc "Register_page" 1
    button $top.but53 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text BACK 
    vTcl:DefineAlias "$top.but53" "Button_back" vTcl:WidgetProc "Register_page" 1
    entry $top.ent54 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 164 
    vTcl:DefineAlias "$top.ent54" "Entry_ID" vTcl:WidgetProc "Register_page" 1
    entry $top.ent55 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 114 
    vTcl:DefineAlias "$top.ent55" "Entry_phone" vTcl:WidgetProc "Register_page" 1
    entry $top.ent56 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 314 
    vTcl:DefineAlias "$top.ent56" "Entry_user" vTcl:WidgetProc "Register_page" 1
    entry $top.ent57 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent57" "Entry_pass" vTcl:WidgetProc "Register_page" 1
    entry $top.ent58 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -insertbackground black -selectbackground blue \
        -selectforeground white -width 10 
    vTcl:DefineAlias "$top.ent58" "Entry_repass" vTcl:WidgetProc "Register_page" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab46 \
        -in $top -x 0 -relx 0.212 -y 0 -rely 0.046 -width 0 -relwidth 0.577 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.212 -y 0 -rely 0.137 -width 0 -relwidth 0.258 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.519 -y 0 -rely 0.137 -width 0 -relwidth 0.258 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.212 -y 0 -rely 0.297 -width 0 -relwidth 0.565 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.212 -y 0 -rely 0.458 -width 0 -relwidth 0.565 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.212 -y 0 -rely 0.618 -width 0 -relwidth 0.565 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.but52 \
        -in $top -x 0 -relx 0.327 -y 0 -rely 0.778 -width 197 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but53 \
        -in $top -x 0 -relx 0.038 -y 0 -rely 0.046 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent54 \
        -in $top -x 0 -relx 0.212 -y 0 -rely 0.195 -width 140 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent55 \
        -in $top -x 0 -relx 0.519 -y 0 -rely 0.195 -width 140 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 0 -relx 0.212 -y 0 -rely 0.355 -width 300 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent57 \
        -in $top -x 0 -relx 0.212 -y 0 -rely 0.515 -width 300 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent58 \
        -in $top -x 0 -relx 0.212 -y 0 -rely 0.675 -width 300 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top5 {base} {
    global vTcl
    if {$base == ""} {
        set base .top5
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #e4e4e4 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 520x476+415+110
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Booking"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Book_page" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    button $top.but46 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text BACK 
    vTcl:DefineAlias "$top.but46" "Button_back" vTcl:WidgetProc "Book_page" 1
    button $top.but61 \
        -activebackground #00ff40 -activeforeground #000000 \
        -background #b3ff66 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text BOOK 
    vTcl:DefineAlias "$top.but61" "Button_book" vTcl:WidgetProc "Book_page" 1
    label $top.lab62 \
        -activebackground #f9f9f9 -activeforeground black -background #e4e4e4 \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Flight details} 
    vTcl:DefineAlias "$top.lab62" "Label_details" vTcl:WidgetProc "Book_page" 1
    label $top.lab63 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Date :} 
    vTcl:DefineAlias "$top.lab63" "Label_due" vTcl:WidgetProc "Book_page" 1
    label $top.lab64 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 00/00/00 
    vTcl:DefineAlias "$top.lab64" "Label_date" vTcl:WidgetProc "Book_page" 1
    label $top.lab65 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Price/Baht :} 
    vTcl:DefineAlias "$top.lab65" "Label_baht" vTcl:WidgetProc "Book_page" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 0000 
    vTcl:DefineAlias "$top.lab47" "Label_price" vTcl:WidgetProc "Book_page" 1
    frame $top.fra54 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 205 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -width 345 
    vTcl:DefineAlias "$top.fra54" "Frame1" vTcl:WidgetProc "Book_page" 1
    set site_3_0 $top.fra54
    label $site_3_0.lab46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {o-----------------------------------> o} 
    vTcl:DefineAlias "$site_3_0.lab46" "Label2_1" vTcl:WidgetProc "Book_page" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 00:00 
    vTcl:DefineAlias "$site_3_0.lab47" "Label_timestart" vTcl:WidgetProc "Book_page" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont -foreground #808080 \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Total trip duration} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label2" vTcl:WidgetProc "Book_page" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text XXX 
    vTcl:DefineAlias "$site_3_0.lab49" "Label_origin" vTcl:WidgetProc "Book_page" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 00:00 
    vTcl:DefineAlias "$site_3_0.lab50" "Label_timearrival" vTcl:WidgetProc "Book_page" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text XXX 
    vTcl:DefineAlias "$site_3_0.lab51" "Label_destination" vTcl:WidgetProc "Book_page" 1
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {xxh xxmin} 
    vTcl:DefineAlias "$site_3_0.lab52" "Label_timeduration" vTcl:WidgetProc "Book_page" 1
    place $site_3_0.lab46 \
        -in $site_3_0 -x 0 -relx 0.149 -y 0 -rely 0.286 -width 0 \
        -relwidth 0.699 -height 0 -relheight 0.177 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 0 -relx 0.116 -y 0 -rely 0.488 -width 0 \
        -relwidth 0.145 -height 0 -relheight 0.122 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.232 -y 0 -rely 0.098 -width 0 \
        -relwidth 0.504 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 0 -relx 0.058 -y 0 -rely 0.634 -width 0 \
        -relwidth 0.261 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 0 -relx 0.696 -y 0 -rely 0.488 -width 0 \
        -relwidth 0.145 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 0 -relx 0.638 -y 0 -rely 0.634 -width 0 \
        -relwidth 0.261 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 0 -relx 0.232 -y 0 -rely 0.195 -width 0 \
        -relwidth 0.504 -height 0 -relheight 0.102 -anchor nw \
        -bordermode ignore 
    button $top.but47 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text History 
    vTcl:DefineAlias "$top.but47" "Button_history" vTcl:WidgetProc "Book_page" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but46 \
        -in $top -x 0 -relx 0.038 -y 0 -rely 0.046 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but61 \
        -in $top -x 0 -relx 0.635 -y 0 -rely 0.206 -width 97 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.192 -y 0 -rely 0.092 -width 0 -relwidth 0.642 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 0 -relx 0.173 -y 0 -rely 0.275 -width 0 -relwidth 0.065 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab64 \
        -in $top -x 0 -relx 0.327 -y 0 -rely 0.275 -width 0 -relwidth 0.142 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.173 -y 0 -rely 0.206 -width 0 -relwidth 0.142 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.327 -y 0 -rely 0.206 -width 0 -relwidth 0.142 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.fra54 \
        -in $top -x 0 -relx 0.173 -y 0 -rely 0.343 -width 0 -relwidth 0.663 \
        -height 0 -relheight 0.469 -anchor nw -bordermode ignore 
    place $top.but47 \
        -in $top -x 0 -relx 0.865 -y 0 -rely 0.046 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top6 {base} {
    global vTcl
    if {$base == ""} {
        set base .top6
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #e4e4e4 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 371x364+826+232
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Payment"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Payment_page" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    button $top.but58 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Cancel 
    vTcl:DefineAlias "$top.but58" "Button_cancel" vTcl:WidgetProc "Payment_page" 1
    button $top.but59 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #b3ff66 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Confirm 
    vTcl:DefineAlias "$top.but59" "Button_confirm" vTcl:WidgetProc "Payment_page" 1
    label $top.lab61 \
        -activebackground #f9f9f9 -activeforeground black -background #e4e4e4 \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Payment 
    vTcl:DefineAlias "$top.lab61" "Label_payment" vTcl:WidgetProc "Payment_page" 1
    label $top.lab62 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text XXX 
    vTcl:DefineAlias "$top.lab62" "Label_origin" vTcl:WidgetProc "Payment_page" 1
    label $top.lab63 \
        -activebackground #f9f9f9 -activeforeground black -background #e4e4e4 \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text > 
    vTcl:DefineAlias "$top.lab63" "Label1" vTcl:WidgetProc "Payment_page" 1
    label $top.lab64 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text XXX 
    vTcl:DefineAlias "$top.lab64" "Label_destination" vTcl:WidgetProc "Payment_page" 1
    label $top.lab65 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Departure :} 
    vTcl:DefineAlias "$top.lab65" "Label_depart" vTcl:WidgetProc "Payment_page" 1
    label $top.lab66 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {Total :} 
    vTcl:DefineAlias "$top.lab66" "Label_total" vTcl:WidgetProc "Payment_page" 1
    label $top.lab67 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 0000 
    vTcl:DefineAlias "$top.lab67" "Label_price" vTcl:WidgetProc "Payment_page" 1
    label $top.lab46 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {User Name :} 
    vTcl:DefineAlias "$top.lab46" "Label_name" vTcl:WidgetProc "Payment_page" 1
    label $top.lab47 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {ID Card :} 
    vTcl:DefineAlias "$top.lab47" "Label_card" vTcl:WidgetProc "Payment_page" 1
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 1234567891234 
    vTcl:DefineAlias "$top.lab48" "Label_ID" vTcl:WidgetProc "Payment_page" 1
    label $top.lab49 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Kunthida 
    vTcl:DefineAlias "$top.lab49" "Label_user" vTcl:WidgetProc "Payment_page" 1
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Baht 
    vTcl:DefineAlias "$top.lab50" "Label_baht" vTcl:WidgetProc "Payment_page" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #e4e4e4 \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text -------------------------------------------------------- 
    vTcl:DefineAlias "$top.lab51" "Label2" vTcl:WidgetProc "Payment_page" 1
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black -background #e4e4e4 \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text -------------------------------------------------------- 
    vTcl:DefineAlias "$top.lab52" "Label2_2" vTcl:WidgetProc "Payment_page" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.but58 \
        -in $top -x 0 -relx 0.243 -y 0 -rely 0.714 -width 77 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but59 \
        -in $top -x 0 -relx 0.539 -y 0 -rely 0.714 -width 77 -relwidth 0 \
        -height 34 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 0 -relx 0.216 -y 0 -rely 0.055 -width 0 -relwidth 0.588 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 0 -relx 0.485 -y 0 -rely 0.412 -width 0 -relwidth 0.067 \
        -height 0 -relheight 0.049 -anchor nw -bordermode ignore 
    place $top.lab63 \
        -in $top -x 0 -relx 0.593 -y 0 -rely 0.412 -width 0 -relwidth 0.065 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab64 \
        -in $top -x 0 -relx 0.674 -y 0 -rely 0.412 -width 0 -relwidth 0.065 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 0 -relx 0.243 -y 0 -rely 0.412 -width 0 -relwidth 0.202 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab66 \
        -in $top -x 0 -relx 0.243 -y 0 -rely 0.522 -width 0 -relwidth 0.202 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab67 \
        -in $top -x 0 -relx 0.485 -y 0 -rely 0.522 -width 0 -relwidth 0.17 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab46 \
        -in $top -x 0 -relx 0.243 -y 0 -rely 0.192 -width 0 -relwidth 0.202 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.243 -y 0 -rely 0.302 -width 0 -relwidth 0.202 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab48 \
        -in $top -x 0 -relx 0.485 -y 0 -rely 0.302 -width 0 -relwidth 0.221 \
        -height 0 -relheight 0.049 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 0 -relx 0.485 -y 0 -rely 0.192 -width 0 -relwidth 0.218 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.674 -y 0 -rely 0.522 -width 0 -relwidth 0.146 \
        -height 0 -relheight 0.047 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.054 -y 0 -rely 0.11 -width 0 -relwidth 0.9 \
        -height 0 -relheight 0.058 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.054 -y 0 -rely 0.604 -width 0 -relwidth 0.9 \
        -height 0 -relheight 0.058 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc vTclWindow.top7 {base} {
    global vTcl
    if {$base == ""} {
        set base .top7
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #e4e4e4 -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 520x437+549+164
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1924 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "History"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "History_page" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Information 
    vTcl:DefineAlias "$top.lab48" "Label1" vTcl:WidgetProc "History_page" 1
    button $top.but50 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background $vTcl(actual_gui_bg) -compound left \
        -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text BACK 
    vTcl:DefineAlias "$top.but50" "Button_back" vTcl:WidgetProc "History_page" 1
    label $top.lab51 \
        -activebackground #f9f9f9 -activeforeground black -background #e4e4e4 \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Price 
    vTcl:DefineAlias "$top.lab51" "Label2" vTcl:WidgetProc "History_page" 1
    label $top.lab52 \
        -activebackground #f9f9f9 -activeforeground black -background #e4e4e4 \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text Status 
    vTcl:DefineAlias "$top.lab52" "Label2" vTcl:WidgetProc "History_page" 1
    label $top.lab53 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {XXX > XXX} 
    vTcl:DefineAlias "$top.lab53" "Label_departure1" vTcl:WidgetProc "History_page" 1
    label $top.lab54 \
        -activebackground #f9f9f9 -activeforeground black -background #e4e4e4 \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 0000 
    vTcl:DefineAlias "$top.lab54" "Label_price1" vTcl:WidgetProc "History_page" 1
    label $top.lab56 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background #e4e4e4 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text {XXX > XXX} 
    vTcl:DefineAlias "$top.lab56" "Label_departure2" vTcl:WidgetProc "History_page" 1
    label $top.lab57 \
        -activebackground #f9f9f9 -activeforeground black -background #e4e4e4 \
        -compound left -disabledforeground #a3a3a3 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -text 0000 
    vTcl:DefineAlias "$top.lab57" "Label_price2" vTcl:WidgetProc "History_page" 1
    button $top.but58 \
        -activebackground #f9f9f9 -activeforeground #000000 \
        -background #eb0214 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground #ffffff \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Cancel 
    vTcl:DefineAlias "$top.but58" "Button1" vTcl:WidgetProc "History_page" 1
    button $top.but59 \
        -activebackground #f9f9f9 -activeforeground #000000 \
        -background #b3ff66 -compound left -disabledforeground #a3a3a3 \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Success 
    vTcl:DefineAlias "$top.but59" "Button1" vTcl:WidgetProc "History_page" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab48 \
        -in $top -x 0 -relx 0.096 -y 0 -rely 0.137 -width 0 -relwidth 0.315 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.but50 \
        -in $top -x 0 -relx 0.038 -y 0 -rely 0.046 -width 47 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 0 -relx 0.538 -y 0 -rely 0.137 -width 0 -relwidth 0.085 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab52 \
        -in $top -x 0 -relx 0.788 -y 0 -rely 0.137 -width 0 -relwidth 0.085 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 0 -relx 0.096 -y 0 -rely 0.229 -width 0 -relwidth 0.162 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 0 -relx 0.538 -y 0 -rely 0.229 -width 0 -relwidth 0.085 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab56 \
        -in $top -x 0 -relx 0.096 -y 0 -rely 0.32 -width 0 -relwidth 0.162 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 0 -relx 0.538 -y 0 -rely 0.32 -width 0 -relwidth 0.085 \
        -height 0 -relheight 0.048 -anchor nw -bordermode ignore 
    place $top.but58 \
        -in $top -x 0 -relx 0.769 -y 0 -rely 0.32 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    place $top.but59 \
        -in $top -x 0 -relx 0.769 -y 0 -rely 0.229 -width 67 -relwidth 0 \
        -height 24 -relheight 0 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}
set btop2 ""
if {$vTcl(borrow)} {
    set btop2 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop2 $vTcl(tops)] != -1} {
        set btop2 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop2
Window show .top2 $btop2
if {$vTcl(borrow)} {
    $btop2 configure -background plum
}
set btop3 ""
if {$vTcl(borrow)} {
    set btop3 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop3 $vTcl(tops)] != -1} {
        set btop3 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop3
Window show .top3 $btop3
if {$vTcl(borrow)} {
    $btop3 configure -background plum
}
set btop4 ""
if {$vTcl(borrow)} {
    set btop4 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop4 $vTcl(tops)] != -1} {
        set btop4 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop4
Window show .top4 $btop4
if {$vTcl(borrow)} {
    $btop4 configure -background plum
}
set btop5 ""
if {$vTcl(borrow)} {
    set btop5 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop5 $vTcl(tops)] != -1} {
        set btop5 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop5
Window show .top5 $btop5
if {$vTcl(borrow)} {
    $btop5 configure -background plum
}
set btop6 ""
if {$vTcl(borrow)} {
    set btop6 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop6 $vTcl(tops)] != -1} {
        set btop6 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop6
Window show .top6 $btop6
if {$vTcl(borrow)} {
    $btop6 configure -background plum
}
set btop7 ""
if {$vTcl(borrow)} {
    set btop7 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop7 $vTcl(tops)] != -1} {
        set btop7 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop7
Window show .top7 $btop7
if {$vTcl(borrow)} {
    $btop7 configure -background plum
}

