#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.3
#  in conjunction with Tcl version 8.6
#    May 12, 2022 02:31:20 AM +07  platform: Windows NT

import tkinter as tk
from tkinter import messagebox
import tkinter.ttk as ttk
from tkinter.constants import *

from PIL import Image, ImageTk

import backend
import Flightpage_support

import main
import ViewFlight_support
import searchGUI

class FlightPageUI:
    def __init__(self, Source, Destination, Date, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        
        top.geometry("800x600+625+291")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1,  1)
        top.title("Toplevel 2")
        top.configure(background="#d9d9d9")
        
        # print(top,Destination,Source,Date)

        self.top = top
        self.destination = Destination
        self.source = Source
        self.date = Date
        

        user = backend.User(backend.Account.getLoginUser())

        
        # backend.User.searchFlight(self.source,self.destination)
        flight = user.searchFlight(self.source,self.destination)

        print(flight)
        print(self.destination)
        print(self.source)

        print(flight[0]["id"])
        print(flight[1]["id"])
        print(flight[2]["id"])

        self.Label1 = tk.Label(self.top)
        self.Label1.place(relx=-0.004, rely=0.0, height=600, width=803)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        
        photo_location = Image.open("listflight.jpg")
        global _img0
        _img0 = ImageTk.PhotoImage(photo_location)
        self.Label1.configure(image=_img0)
        self.Label1.configure(text='''Label''')
        

        self.Label_from = tk.Label(self.top)
        self.Label_from.place(relx=0.275, rely=0.153, height=31, width=316)
        self.Label_from.configure(activebackground="#f9f9f9")
        self.Label_from.configure(activeforeground="black")
        self.Label_from.configure(anchor='w')
        self.Label_from.configure(background="#627d96")
        self.Label_from.configure(compound='left')
        self.Label_from.configure(font="-family {Arial} -size 16")
        self.Label_from.configure(foreground="#ffffff")
        self.Label_from.configure(text=self.source)

        self.Button_back = tk.Button(self.top)
        self.Button_back.place(relx=0.063, rely=0.06, height=44, width=47)
        self.Button_back.configure(activebackground="#ececec")
        self.Button_back.configure(activeforeground="#000000")
        self.Button_back.configure(background="#d9d9d9")
        self.Button_back.configure(compound='left')
        self.Button_back.configure(foreground="#000000")
        self.Button_back.configure(pady="0")
        self.Button_back.configure(text='''Back''')
        self.Button_back.configure(command=self.back)

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.063, rely=0.333, relheight=0.133, relwidth=0.85)

        self.Frame1.configure(relief='flat')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(background="#ffffff")

        self.Button_choose_1 = tk.Button(self.Frame1)
        self.Button_choose_1.place(relx=0.707, rely=0.25, height=44, width=167)
        self.Button_choose_1.configure(activebackground="#ffffff")
        self.Button_choose_1.configure(activeforeground="#7ed957")
        self.Button_choose_1.configure(background="#7ed957")
        self.Button_choose_1.configure(compound='left')
        self.Button_choose_1.configure(font="-family {Arial} -size 15")
        self.Button_choose_1.configure(foreground="#ffffff")
        self.Button_choose_1.configure(pady="0")
        self.Button_choose_1.configure(text='''CHOOSE''')
        command = None
        command= lambda arg1=self.source,arg2=flight[0]["id"],arg3=self.date : self.sendtobook(arg1,arg2,arg3)
        self.Button_choose_1.configure(command=command)

        self.Label_timestart = tk.Label(self.Frame1)
        self.Label_timestart.place(relx=0.074, rely=0.25, height=21, width=85)
        self.Label_timestart.configure(background="#ffffff")
        self.Label_timestart.configure(compound='left')
        self.Label_timestart.configure(font="-family {Arial} -size 13")
        self.Label_timestart.configure(foreground="#000000")
        self.Label_timestart.configure(text=flight[0]["start"])

        self.Label3_2_1 = tk.Label(self.Frame1)
        self.Label3_2_1.place(relx=0.221, rely=0.125, height=41, width=43)
        self.Label3_2_1.configure(background="#ffffff")
        self.Label3_2_1.configure(compound='left')
        self.Label3_2_1.configure(font="-family {Segoe UI} -size 16")
        self.Label3_2_1.configure(foreground="#000000")
        self.Label3_2_1.configure(text='''>''')

        self.Label_origin = tk.Label(self.Frame1)
        self.Label_origin.place(relx=0.074, rely=0.625, height=21, width=85)
        self.Label_origin.configure(background="#ffffff")
        self.Label_origin.configure(compound='left')
        self.Label_origin.configure(font="-family {Arial} -size 13")
        self.Label_origin.configure(foreground="#000000")
        self.Label_origin.configure(text=self.source)

        self.Label_timearrival = tk.Label(self.Frame1)
        self.Label_timearrival.place(relx=0.31, rely=0.25, height=21, width=84)
        self.Label_timearrival.configure(background="#ffffff")
        self.Label_timearrival.configure(compound='left')
        self.Label_timearrival.configure(font="-family {Arial} -size 13")
        self.Label_timearrival.configure(foreground="#000000")
        self.Label_timearrival.configure(text=flight[0]["end"])

        self.Label_destination = tk.Label(self.Frame1)
        self.Label_destination.place(relx=0.309, rely=0.625, height=21, width=85)
        self.Label_destination.configure(background="#ffffff")
        self.Label_destination.configure(compound='left')
        self.Label_destination.configure(font="-family {Arial} -size 13")
        self.Label_destination.configure(foreground="#000000")
        self.Label_destination.configure(text=flight[0]["name"])

        self.Label_baht = tk.Label(self.Frame1)
        self.Label_baht.place(relx=0.559, rely=0.625, height=21, width=85)
        self.Label_baht.configure(background="#ffffff")
        self.Label_baht.configure(compound='left')
        self.Label_baht.configure(font="-family {Arial} -size 10")
        self.Label_baht.configure(foreground="#a0a0a0")
        self.Label_baht.configure(text='''Baht''')

        self.Label_price = tk.Label(self.Frame1)
        self.Label_price.place(relx=0.559, rely=0.25, height=21, width=85)
        self.Label_price.configure(background="#ffffff")
        self.Label_price.configure(compound='left')
        self.Label_price.configure(font="-family {Arial} -size 15 -weight bold")
        self.Label_price.configure(foreground="#000000")
        self.Label_price.configure(text=flight[0]["price"])

        self.Frame2 = tk.Frame(self.top)
        self.Frame2.place(relx=0.063, rely=0.533, relheight=0.133, relwidth=0.85)

        self.Frame2.configure(relief='flat')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(background="#ffffff")

        self.Button_choose_1_1 = tk.Button(self.Frame2)
        self.Button_choose_1_1.place(relx=0.707, rely=0.25, height=44, width=167)
        self.Button_choose_1_1.configure(activebackground="#ffffff")
        self.Button_choose_1_1.configure(activeforeground="#7ed957")
        self.Button_choose_1_1.configure(background="#7ed957")
        self.Button_choose_1_1.configure(compound='left')
        self.Button_choose_1_1.configure(font="-family {Arial} -size 15")
        self.Button_choose_1_1.configure(foreground="#ffffff")
        self.Button_choose_1_1.configure(pady="0")
        self.Button_choose_1_1.configure(text='''CHOOSE''')
        command= lambda arg1=self.source,arg2=flight[1]["id"],arg3=self.date : self.sendtobook(arg1,arg2,arg3)
        self.Button_choose_1_1.configure(command=command)

        self.Label_timestart_1 = tk.Label(self.Frame2)
        self.Label_timestart_1.place(relx=0.074, rely=0.25, height=21, width=85)
        self.Label_timestart_1.configure(background="#ffffff")
        self.Label_timestart_1.configure(compound='left')
        self.Label_timestart_1.configure(font="-family {Arial} -size 13")
        self.Label_timestart_1.configure(foreground="#000000")
        self.Label_timestart_1.configure(text=flight[1]["start"])

        self.Label3_2_1_1 = tk.Label(self.Frame2)
        self.Label3_2_1_1.place(relx=0.221, rely=0.125, height=41, width=43)
        self.Label3_2_1_1.configure(background="#ffffff")
        self.Label3_2_1_1.configure(compound='left')
        self.Label3_2_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Label3_2_1_1.configure(foreground="#000000")
        self.Label3_2_1_1.configure(text='''>''')

        self.Label_origin_1 = tk.Label(self.Frame2)
        self.Label_origin_1.place(relx=0.074, rely=0.625, height=21, width=85)
        self.Label_origin_1.configure(background="#ffffff")
        self.Label_origin_1.configure(compound='left')
        self.Label_origin_1.configure(font="-family {Arial} -size 13")
        self.Label_origin_1.configure(foreground="#000000")
        self.Label_origin_1.configure(text=self.source)

        self.Label_timearrival_1 = tk.Label(self.Frame2)
        self.Label_timearrival_1.place(relx=0.31, rely=0.25, height=21, width=84)
        self.Label_timearrival_1.configure(background="#ffffff")
        self.Label_timearrival_1.configure(compound='left')
        self.Label_timearrival_1.configure(font="-family {Arial} -size 13")
        self.Label_timearrival_1.configure(foreground="#000000")
        self.Label_timearrival_1.configure(text=flight[1]["end"])

        self.Label_destination_1 = tk.Label(self.Frame2)
        self.Label_destination_1.place(relx=0.309, rely=0.625, height=21
                , width=85)
        self.Label_destination_1.configure(background="#ffffff")
        self.Label_destination_1.configure(compound='left')
        self.Label_destination_1.configure(font="-family {Arial} -size 13")
        self.Label_destination_1.configure(foreground="#000000")
        self.Label_destination_1.configure(text=flight[1]["name"])

        self.Label_baht_1 = tk.Label(self.Frame2)
        self.Label_baht_1.place(relx=0.559, rely=0.625, height=21, width=85)
        self.Label_baht_1.configure(background="#ffffff")
        self.Label_baht_1.configure(compound='left')
        self.Label_baht_1.configure(font="-family {Arial} -size 10")
        self.Label_baht_1.configure(foreground="#a0a0a0")
        self.Label_baht_1.configure(text='''Baht''')

        self.Label_price_1 = tk.Label(self.Frame2)
        self.Label_price_1.place(relx=0.559, rely=0.25, height=21, width=85)
        self.Label_price_1.configure(background="#ffffff")
        self.Label_price_1.configure(compound='left')
        self.Label_price_1.configure(font="-family {Arial} -size 15 -weight bold")
        self.Label_price_1.configure(foreground="#000000")
        self.Label_price_1.configure(text=flight[1]["price"])

        self.Frame2_1 = tk.Frame(self.top)
        self.Frame2_1.place(relx=0.063, rely=0.733, relheight=0.133
                , relwidth=0.85)
        self.Frame2_1.configure(relief='flat')
        self.Frame2_1.configure(borderwidth="2")
        self.Frame2_1.configure(background="#ffffff")

        self.Button_choose_1_1_1 = tk.Button(self.Frame2_1)
        self.Button_choose_1_1_1.place(relx=0.707, rely=0.25, height=44
                , width=167)
        self.Button_choose_1_1_1.configure(activebackground="#ffffff")
        self.Button_choose_1_1_1.configure(activeforeground="#7ed957")
        self.Button_choose_1_1_1.configure(background="#7ed957")
        self.Button_choose_1_1_1.configure(compound='left')
        self.Button_choose_1_1_1.configure(font="-family {Arial} -size 15")
        self.Button_choose_1_1_1.configure(foreground="#ffffff")
        self.Button_choose_1_1_1.configure(pady="0")
        self.Button_choose_1_1_1.configure(text='''CHOOSE''')
        command= lambda arg1=self.source,arg2=flight[2]["id"],arg3=self.date : self.sendtobook(arg1,arg2,arg3)
        self.Button_choose_1_1_1.configure(command=command)

        self.Label_timestart_1_1 = tk.Label(self.Frame2_1)
        self.Label_timestart_1_1.place(relx=0.074, rely=0.25, height=21
                , width=85)
        self.Label_timestart_1_1.configure(background="#ffffff")
        self.Label_timestart_1_1.configure(compound='left')
        self.Label_timestart_1_1.configure(font="-family {Arial} -size 13")
        self.Label_timestart_1_1.configure(foreground="#000000")
        self.Label_timestart_1_1.configure(text=flight[2]["start"])

        self.Label3_2_1_1_1 = tk.Label(self.Frame2_1)
        self.Label3_2_1_1_1.place(relx=0.221, rely=0.125, height=41, width=43)
        self.Label3_2_1_1_1.configure(background="#ffffff")
        self.Label3_2_1_1_1.configure(compound='left')
        self.Label3_2_1_1_1.configure(font="-family {Segoe UI} -size 16")
        self.Label3_2_1_1_1.configure(foreground="#000000")
        self.Label3_2_1_1_1.configure(text='''>''')

        self.Label_origin_1_1 = tk.Label(self.Frame2_1)
        self.Label_origin_1_1.place(relx=0.074, rely=0.625, height=21, width=85)
        self.Label_origin_1_1.configure(background="#ffffff")
        self.Label_origin_1_1.configure(compound='left')
        self.Label_origin_1_1.configure(font="-family {Arial} -size 13")
        self.Label_origin_1_1.configure(foreground="#000000")
        self.Label_origin_1_1.configure(text=self.source)

        self.Label_timearrival_1_1 = tk.Label(self.Frame2_1)
        self.Label_timearrival_1_1.place(relx=0.31, rely=0.25, height=21
                , width=84)
        self.Label_timearrival_1_1.configure(background="#ffffff")
        self.Label_timearrival_1_1.configure(compound='left')
        self.Label_timearrival_1_1.configure(font="-family {Arial} -size 13")
        self.Label_timearrival_1_1.configure(foreground="#000000")
        self.Label_timearrival_1_1.configure(text=flight[2]["end"])

        self.Label_destination_1_1 = tk.Label(self.Frame2_1)
        self.Label_destination_1_1.place(relx=0.309, rely=0.625, height=21
                , width=85)
        self.Label_destination_1_1.configure(background="#ffffff")
        self.Label_destination_1_1.configure(compound='left')
        self.Label_destination_1_1.configure(font="-family {Arial} -size 13")
        self.Label_destination_1_1.configure(foreground="#000000")
        self.Label_destination_1_1.configure(text=flight[2]["name"])

        self.Label_baht_1_1 = tk.Label(self.Frame2_1)
        self.Label_baht_1_1.place(relx=0.559, rely=0.625, height=21, width=85)
        self.Label_baht_1_1.configure(background="#ffffff")
        self.Label_baht_1_1.configure(compound='left')
        self.Label_baht_1_1.configure(font="-family {Arial} -size 10")
        self.Label_baht_1_1.configure(foreground="#a0a0a0")
        self.Label_baht_1_1.configure(text='''Baht''')

        self.Label_price_1_1 = tk.Label(self.Frame2_1)
        self.Label_price_1_1.place(relx=0.559, rely=0.25, height=21, width=85)
        self.Label_price_1_1.configure(background="#ffffff")
        self.Label_price_1_1.configure(compound='left')
        self.Label_price_1_1.configure(font="-family {Arial} -size 15 -weight bold")
        self.Label_price_1_1.configure(foreground="#000000")
        self.Label_price_1_1.configure(text=flight[2]["price"])

        self.Label_to = tk.Label(self.top)
        self.Label_to.place(relx=0.125, rely=0.207, height=31, width=416)
        self.Label_to.configure(anchor='w')
        self.Label_to.configure(background="#627d96")
        self.Label_to.configure(compound='left')
        self.Label_to.configure(font="-family {Arial} -size 16")
        self.Label_to.configure(foreground="#ffffff")
        self.Label_to.configure(text=self.destination)
        
    def back(self):
        main.changePage(self.top,searchGUI.search_page)
        
    def sendtobook(self,source,destination,date):
        if(backend.Account.getLoginUser() != "0"):
            self.top.destroy()
            ViewFlight_support.main(source,destination,date)
        else:
            messagebox.showerror("ERROR", "This page is not allowed for guest")


def start_up():
    Flightpage_support.main()

if __name__ == '__main__':
    Flightpage_support.main()
